name: Build python engine

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install requirements
        run: pip install -r ./requirements.txt

      - name: upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: install flask
        run: python -m pip install flask
        
      - name: run flask
        run:
          set FLASK_APP=Backend
          python -m flask run
          
      - name: run Unit and Integration testing
        run:
            pip install pytest
            pip install pytest-cov
            python main.py
